baseURL = "http://example.org/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "cv/resume"
    author = "ngoe gaiel"
    description = "My portfolio"
    copyright = "copyright 2024"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Ngoe Gaiel"
        title = "Abbr.,N.G."
        photo = "/images/profile-image.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "#"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/Ngoe-Gaiel"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "#"
        title = "ResearchGate"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Advance level"
        college = "Inter Comprehensive High School"
        dates = "2022 - 2023"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "ordinary level"
        college = "Inter Comprehensive High School"
        dates = "2021- 2022"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "French"
        level = "Basic"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Dancing"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Reading"


        [[params.hobbies.list]]
        interest = "gaming"

    [params.aboutme]
        description = "My name is Ngoe Gaiel,i am a level 200 student at Landmark university with a strong interest in web development.i'm driven by a desire to build innovative solutions,and a passion for problem solvng.i'm excited to apply my skills and knowledge to real world projects and contribute to building user friendly websites."




    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Personal portfolio(cv/resume)"
        url = "#"
        description = "this project contains a brief introduction of my about,education,social media platforms and more "
		
		[[params.projects.list]]
        title = "Host on github pages using hugo"
        url = "https://github.com/Ngoe-Gaiel"
        description = "this consist of all the various steps and technologies used like html,node.js etc used in creating this project,the challenges faced,solutions used in solving them and finally the outcome."

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "html"
        skillrating = 50 # out of 100
                
        [[params.skills.list]]
        skill = "c programming"
        skillrating = 45
		
        [[params.skills.list]]
        skill = "c#"
        skillrating = 60

